### ISSUE TITLE
Firefox UI issues

### ISSUE THREAD

**Issue by esube** [brollb/deepforge#190]
After installing and running the app, created a test project.
After creating the project, the startup UI that shows architecture, models, data wouldn't load on firefox. 
I tried to connect to the app using chrome and just loaded the already created 'test' project and the UI loaded correctly. See attached image. 

Also, webgme gives the following error:
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version

And this error repeats itself on the interactive console every time
![chrome-firefox](https://cloud.githubusercontent.com/assets/7385894/12270359/a999715a-b923-11e5-920a-0fa3dfd389e6.png)
 you perform an action on the web interface such as creating a new project, etc...

**Comment by brollb** [comment]
It looks like Firefox doesn't support `let` yet https://bugzilla.mozilla.org/show_bug.cgi?id=950547
