### ISSUE TITLE
Connection remains after layer is deleted. 

### ISSUE THREAD

**Issue by JimnyCricket** [brollb/deepforge#9]
After deleting a layer, the connection remains (hidden). The code cannot run because of a missed connection. If the page is reloaded a box with the connection appears, and can then be deleted.

**Comment by brollb** [comment]
This is based in the WebGME. I am asking around to figure out why this is the current behavior (maybe it is just a bug we can get fixed there).

Otherwise I might remove these "dangling" edges in the plugin before loading the Torch or Caffe generators.

**Comment by brollb** [comment]
This is no longer relevant after creating the custom visualizer
